# Generated by Django 5.1.4 on 2025-01-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='binary',
            field=models.BinaryField(default=b''),
        ),
    ]
