# Generated by Django 5.1.4 on 2025-01-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_uploadedimage_binary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='binary',
            field=models.BinaryField(),
        ),
    ]
